"""create ratings table

Revision ID: 52f7ff0bbb01
Revises: 
Create Date: 2026-01-15 20:57:07.945049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f7ff0bbb01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_tmdb_movie_id'), ['tmdb_movie_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_tmdb_movie_id'))

    op.drop_table('notas')
    # ### end Alembic commands ###
