"""drop unique index on tmdb_movie_id

Revision ID: aca7af88c4ae
Revises: 6be0f468ec76
Create Date: 2026-01-17 20:48:36.031430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca7af88c4ae'
down_revision = '6be0f468ec76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_tmdb_movie_id'))
        batch_op.create_index(batch_op.f('ix_ratings_tmdb_movie_id'), ['tmdb_movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_tmdb_movie_id'))
        batch_op.create_index(batch_op.f('ix_ratings_tmdb_movie_id'), ['tmdb_movie_id'], unique=True)

    # ### end Alembic commands ###
